export default function handler(req, res) {
  return res.status(200).json({
    Breakfast: [
      {
        name: "Chia Cherry Smoothie",
        servings: 1,
        ingredients: [
          "3/4 cup frozen cherries",
          "3/4 cup plain kefir",
          "1/4 tsp cinnamon",
          "1 tbsp chia seeds",
          "1/4 - 1/2 cup water",
          "2 tbsp almonds",
        ],
        prep_time: "2 minutes",
        cooking_time: "0 minutes",
        directions:
          "Blend cherries, kefir, cinnamon, chia seeds, and water. Serve with almonds.",
        nutrition: {
          calories: 445,
          carbohydrates: "60g",
          protein: "22g",
          fat: "15g",
        },
      },
      {
        name: "Cinnamon Chia Pudding",
        servings: 1,
        ingredients: [
          "2 tbsp chia seeds",
          "1 cup almond milk",
          "1/4 tsp ground cinnamon",
          "1/2 tsp vanilla extract",
          "1/2 tbsp honey",
          "1/4 cup blueberries",
          "1/2 cup strawberries",
          "2 tbsp slivered almonds",
        ],
        prep_time: "3 minutes",
        cooking_time: "0 minutes",
        directions:
          "Combine chia seeds, almond milk, cinnamon, vanilla, and honey. Let sit, refrigerate overnight. Top with berries and almonds.",
        nutrition: {
          calories: 344,
          carbohydrates: "42g",
          protein: "9g",
          fat: "17g",
        },
      },
      {
        name: "Coco Mint Strawberry Smoothie",
        servings: 1,
        ingredients: [
          "1 cup almond milk",
          "1 tbsp almond butter",
          "3/4 cup strawberries",
          "1 tbsp cacao nibs",
          "1 scoop collagen peptides",
          "1 tbsp hemp hearts",
          "spinach",
          "cinnamon",
          "1 tsp honey",
        ],
        prep_time: "5 minutes",
        cooking_time: "0 minutes",
        directions: "Blend all ingredients until smooth.",
        nutrition: {
          calories: 387,
          carbohydrates: "32g",
          protein: "19g",
          fat: "21g",
        },
      },
      {
        name: "Eggless Breakfast Hash",
        servings: 2,
        ingredients: [
          "1 tbsp ghee",
          "2 cups sweet potato",
          "1/4 cup white onion",
          "2 cups zucchini",
          "mushrooms",
          "ribeye meat",
          "salt",
          "pepper",
        ],
        prep_time: "10 minutes",
        cooking_time: "25-30 minutes",
        directions:
          "SautÃ© sweet potatoes, onions, and zucchini. Cook ribeye separately, then mix with veggies.",
        nutrition: {
          calories: 407,
          carbohydrates: "35g",
          protein: "30g",
          fat: "17g",
        },
      },
      {
        name: "Green Collagen Smoothie",
        servings: 1,
        ingredients: [
          "1 cup almond milk",
          "collagen powder",
          "2 cups spinach",
          "1/2 cup apple",
          "1/2 cup avocado",
          "frozen mango",
          "flaxseed",
          "ice",
        ],
        prep_time: "5 minutes",
        cooking_time: "0 minutes",
        directions: "Blend all ingredients until creamy.",
        nutrition: {
          calories: 362,
          carbohydrates: "39g",
          protein: "24g",
          fat: "15g",
        },
      },
      {
        name: "Protein Granola Bars",
        servings: 4,
        ingredients: [
          "Almond butter",
          "honey",
          "collagen powder",
          "water",
          "rolled oats",
          "coconut flakes",
          "chia seeds",
        ],
        prep_time: "10 minutes",
        freeze_time: "1-2 hours",
        nutrition: {
          calories: 494,
          carbohydrates: "46g",
          protein: "21g",
          fat: "29g",
        },
      },
      {
        name: "Shredded Brussels & Salmon",
        servings: 1,
        ingredients: [
          "Shredded brussels sprouts",
          "avocado oil",
          "turmeric",
          "salt",
          "pepper",
          "avocado",
          "raw sushi-grade or smoked salmon",
        ],
        prep_time: "5 minutes",
        cooking_time: "5-10 minutes",
        nutrition: {
          calories: 419,
          carbohydrates: "29g",
          protein: "25g",
          fat: "26g",
        },
      },
      {
        name: "Strawberry Overnight Oats",
        servings: 1,
        ingredients: [
          "Rolled oats",
          "almond milk",
          "chopped walnuts",
          "chia seeds",
          "plain Kefir or Greek yogurt",
          "chopped strawberries",
          "honey",
          "optional strawberries for topping",
        ],
        prep_time: "5 minutes",
        cooking_time: "0 minutes",
        nutrition: {
          calories: 386,
          carbohydrates: "58g",
          protein: "15g",
          fat: "12g",
        },
      },
      {
        name: "Turkey and Veggie Skillet",
        servings: 1,
        ingredients: [
          "Avocado oil",
          "sweet potatoes",
          "red bell pepper",
          "onion",
          "fresh dill",
          "salt",
          "pepper",
          "garlic",
          "ground turkey",
          "lemon juice",
          "baby spinach",
        ],
        prep_time: "5 minutes",
        cooking_time: "10-15 minutes",
        nutrition: {
          calories: 424,
          carbohydrates: "34g",
          protein: "32g",
          fat: "18g",
        },
      },
      {
        name: "Very Berry Yogurt Bowl",
        servings: 1,
        ingredients: [
          "Low-fat plain Greek yogurt",
          "raspberries",
          "chopped walnuts",
          "blueberries",
          "cinnamon",
        ],
        prep_time: "5 minutes",
        cooking_time: "0 minutes",
        nutrition: {
          calories: 415,
          carbohydrates: "32g",
          protein: "43g",
          fat: "15g",
        },
      },
    ],
  });
}
