// List of available allergies with types and descriptions
const settings = [
  { value: "Font Size", src: "/icons/add.png", alt: "add icon" },
  { value: "Use Bold Text", src: "/icons/bold.png", alt: "capital b" },
  { value: "Dark Mode", src: "/icons/day-and-night.png", alt: "dark mode" },
  {
    value: "Use Descriptive Links",
    src: "/icons/information.png",
    alt: "Descriptive Links",
  },
  {
    value: "High Contrast Mode",
    src: "/icons/adjustment.png",
    alt: "High contrast mode",
  },
  { value: "Alt for images", src: "/icons/image.png", alt: "alt for images" },
];

// List of available allergies with types and descriptions
const AllergiesInformation = [
  { type: "Peanuts", description: "Allergic to peanuts." },
  { type: "Tree Nuts", description: "Allergic to tree nuts." },
  { type: "Milk", description: "Lactose or milk allergy." },
  { type: "Mustard", description: "Allergic to mustard." },
  { type: "Fish", description: "Allergic to fish." },
  { type: "Egg", description: "Allergic to eggs." },
  { type: "Soy", description: "Allergic to soy products." },
  { type: "Wheat", description: "Wheat or gluten allergy." },
  { type: "Sesame", description: "Allergic to sesame seeds." },
  { type: "Corn", description: "Allergic to corn products." },
  { type: "Shellfish", description: "Allergic to shellfish." },
  { type: "Meat", description: "Allergic to meat products." },
];

// List of available allergies with types and descriptions
const chronicConditions = [
  {
    type: "IBS",
    description:
      "Irritable bowel syndrome (IBS) is a common condition that affects the digestive system.",
  },
  { type: "Diabetes", description: "Affects blood sugar regulation." },
  { type: "Hypertension", description: "High blood pressure." },
  {
    type: "Asthma",
    description: "Respiratory condition causing breathing difficulties.",
  },
  { type: "Heart Disease", description: "Cardiovascular health issues." },
  { type: "Arthritis", description: "Inflammation of the joints." },
  { type: "Cancer", description: "Abnormal cell growth." },
  {
    type: "Alzheimer's",
    description: "Progressive memory loss and cognitive decline.",
  },
  { type: "Chronic Pain", description: "Persistent, long-term pain." },
  { type: "Osteoporosis", description: "Weakening of bones." },
  { type: "Obesity", description: "Excessive body weight." },
  {
    type: "Chronic Kidney Disease",
    description: "Kidney function impairment.",
  },
  { type: "COPD", description: "Chronic lung diseases like emphysema." },
];

// dietery restrictions array and it's descriptions
const foodTypeInformation = [
  { type: "Vegan", description: "No animal products." },
  { type: "Vegetarian", description: "Plant-based diet without meat." },
  { type: "Omnivore", description: "Eats both plants and animals." },
  {
    type: "Paleo",
    description: "Emphasizes whole foods, like our ancestors.",
  },
  { type: "Pescatarian", description: "Vegetarian with fish and seafood." },
  { type: "Carnivore", description: "Primarily meat-based diet." },
  {
    type: "Flexitarian",
    description: "Mainly plant-based with occasional meat.",
  },
  { type: "Keto", description: "High-fat, low-carb diet for ketosis." },
  { type: "Gluten-free", description: "Avoids gluten-containing foods." },
  { type: "Lactose-free", description: "Avoids lactose in dairy products." },
  { type: "Dairy-free", description: "Excludes all dairy products." },
  {
    type: "Shellfish-free",
    description: "Avoids shellfish due to allergies.",
  },
  { type: "Soy-free", description: "Excludes soy-based foods." },
  { type: "Allergen-free", description: "Avoids common allergens." },
  { type: "Low-carb", description: "Restricts carbohydrates." },
  { type: "Mediterranean", description: "Based on Mediterranean cuisine." },
  { type: "Low-fat", description: "Emphasizes low-fat foods." },
  { type: "Low-sugar", description: "Limits sugar intake." },
  { type: "Low-food", description: "Reduces overall food consumption." },
];

//This holds the recipes that Dr Gostic wrote.
const pinnedRecipes = [
  {
    name: "Chia Cherry Smoothie",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "3/4 cup frozen cherries",
      "3/4 cup plain kefir",
      "1/4 tsp cinnamon",
      "1 tbsp chia seeds",
      "1/4 - 1/2 cup water",
      "2 tbsp almonds",
    ],
    prep_time: "2 minutes",
    cooking_time: "0 minutes",
    directions:
      "Blend cherries, kefir, cinnamon, chia seeds, and water. Serve with almonds.",
    nutrition: {
      calories: 445,
      carbohydrates: 60,
      protein: 22,
      fat: 15,
    },
  },
  {
    name: "Cinnamon Chia Pudding",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "2 tbsp chia seeds",
      "1 cup almond milk",
      "1/4 tsp ground cinnamon",
      "1/2 tsp vanilla extract",
      "1/2 tbsp honey",
      "1/4 cup blueberries",
      "1/2 cup strawberries",
      "2 tbsp slivered almonds",
    ],
    prep_time: "3 minutes",
    cooking_time: "0 minutes",
    directions:
      "Combine chia seeds, almond milk, cinnamon, vanilla, and honey. Let sit, refrigerate overnight. Top with berries and almonds.",
    nutrition: {
      calories: 344,
      carbohydrates: 42,
      protein: 9,
      fat: 17,
    },
  },
  {
    name: "Coco Mint Strawberry Smoothie",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "1 cup almond milk",
      "1 tbsp almond butter",
      "3/4 cup strawberries",
      "1 tbsp cacao nibs",
      "1 scoop collagen peptides",
      "1 tbsp hemp hearts",
      "spinach",
      "cinnamon",
      "1 tsp honey",
    ],
    prep_time: "5 minutes",
    cooking_time: "0 minutes",
    directions: "Blend all ingredients until smooth.",
    nutrition: {
      calories: 387,
      carbohydrates: 32,
      protein: 19,
      fat: 21,
    },
  },
  {
    name: "Eggless Breakfast Hash",
    type: "breakfast",
    servings: 2,
    ingredients: [
      "1 tbsp ghee",
      "2 cups sweet potato",
      "1/4 cup white onion",
      "2 cups zucchini",
      "mushrooms",
      "ribeye meat",
      "salt",
      "pepper",
    ],
    prep_time: "10 minutes",
    cooking_time: "25-30 minutes",
    directions:
      "Sauté sweet potatoes, onions, and zucchini. Cook ribeye separately, then mix with veggies.",
    nutrition: {
      calories: 407,
      carbohydrates: 35,
      protein: 30,
      fat: 17,
    },
  },
  {
    name: "Green Collagen Smoothie",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "1 cup almond milk",
      "collagen powder",
      "2 cups spinach",
      "1/2 cup apple",
      "1/2 cup avocado",
      "frozen mango",
      "flaxseed",
      "ice",
    ],
    prep_time: "5 minutes",
    cooking_time: "0 minutes",
    directions: "Blend all ingredients until creamy.",
    nutrition: {
      calories: 362,
      carbohydrates: 39,
      protein: 24,
      fat: 15,
    },
  },
  {
    name: "Protein Granola Bars",
    type: "breakfast",
    servings: 4,
    ingredients: [
      "Almond butter",
      "honey",
      "collagen powder",
      "water",
      "rolled oats",
      "coconut flakes",
      "chia seeds",
    ],
    prep_time: "10 minutes",
    freeze_time: "1-2 hours",
    nutrition: {
      calories: 494,
      carbohydrates: 46,
      protein: 21,
      fat: 29,
    },
  },
  {
    name: "Shredded Brussels & Salmon",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "Shredded brussels sprouts",
      "avocado oil",
      "turmeric",
      "salt",
      "pepper",
      "avocado",
      "raw sushi-grade or smoked salmon",
    ],
    prep_time: "5 minutes",
    cooking_time: "5-10 minutes",
    nutrition: {
      calories: 419,
      carbohydrates: 29,
      protein: 25,
      fat: 26,
    },
  },
  {
    name: "Strawberry Overnight Oats",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "Rolled oats",
      "almond milk",
      "chopped walnuts",
      "chia seeds",
      "plain Kefir or Greek yogurt",
      "chopped strawberries",
      "honey",
      "optional strawberries for topping",
    ],
    prep_time: "5 minutes",
    cooking_time: "0 minutes",
    nutrition: {
      calories: 386,
      carbohydrates: 58,
      protein: 15,
      fat: 12,
    },
  },
  {
    name: "Turkey and Veggie Skillet",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "Avocado oil",
      "sweet potatoes",
      "red bell pepper",
      "onion",
      "fresh dill",
      "salt",
      "pepper",
      "garlic",
      "ground turkey",
      "lemon juice",
      "baby spinach",
    ],
    prep_time: "5 minutes",

    cooking_time: "10-15 minutes",
    nutrition: {
      calories: 424,
      carbohydrates: 34,
      protein: 32,
      fat: 18,
    },
  },
  {
    name: "Very Berry Yogurt Bowl",
    type: "breakfast",
    servings: 1,
    ingredients: [
      "Low-fat plain Greek yogurt",
      "raspberries",
      "chopped walnuts",
      "blueberries",
      "cinnamon",
    ],
    prep_time: "5 minutes",
    cooking_time: "0 minutes",
    nutrition: {
      calories: 415,
      carbohydrates: 32,
      protein: 43,
      fat: 15,
    },
  },

  {
    name: "Asian Style Salad With Grass-fed Steak",
    type: "lunch",
    servings: 2,
    ingredients: [
      "Grass-fed steak",
      "avocado oil",
      "purple and green cabbage with carrots",
      "bean sprouts",
      "edamame",
      "scallion stalks",
      "fresh cilantro",
      "avocado",
      "sesame oil",
      "rice vinegar",
      "soy sauce",
      "lime juice",
      "honey",
      "garlic",
      "ginger",
      "dry roasted cashews",
    ],
    prep_time: "10 minutes",
    cooking_time: "20 minutes",
    nutrition: {
      calories: 542,
      carbohydrates: 23,
      protein: 30,
      fat: 38,
    },
  },
  {
    name: "Balsamic Chicken & Burrata Salad",
    type: "lunch",
    servings: 1,
    ingredients: [
      "Raw spinach",
      "roasted red beets",
      "walnuts",
      "chicken breast",
      "burrata cheese",
      "balsamic glaze",
      "olive oil",
      "salt",
      "pepper",
    ],
    prep_time: "5 minutes",
    cooking_time: "0 minutes",
    nutrition: {
      calories: 493,
      carbohydrates: 29,
      protein: 43,
      fat: 23,
    },
  },
  {
    name: "Chicken Cucumber Boats",
    type: "lunch",
    servings: 1,
    ingredients: [
      "Canned organic chicken",
      "olive oil",
      "ground ginger",
      "turmeric",
      "black pepper",
      "salt",
      "chopped red bell pepper",
      "red onion",
      "cucumber",
      "microgreens",
      "pistachios",
    ],
    prep_time: "10 minutes",
    cooking_time: "0 minutes",
    nutrition: {
      calories: 453,
      carbohydrates: 16,
      protein: 37,
      fat: 27,
    },
  },
  {
    name: "Ginger Tahini Chicken Salad",
    type: "lunch",
    servings: 1,
    ingredients: [
      "Shredded cabbage",
      "slivered almonds",
      "chopped cilantro",
      "orange bell pepper",
      "red onion",
      "canned chickpeas",
      "pre-cooked chicken breast",
      "tahini",
      "fresh grated ginger",
      "coconut aminos",
      "olive oil",
      "sesame oil",
    ],
    prep_time: "10 minutes",
    cooking_time: "0 minutes",
    nutrition: {
      calories: 445,
      carbohydrates: 23,
      protein: 34,
      fat: 25,
    },
  },
  {
    name: "Lentil Curry",
    type: "lunch",
    servings: 2,
    ingredients: [
      "Olive oil",
      "onion",
      "garlic",
      "ginger",
      "curry powder",
      "turmeric",
      "tomatoes",
      "brown lentils",
      "coconut milk",
      "bone broth",
      "fresh spinach",
      "salt",
      "pepper",
    ],
    prep_time: "15 minutes",
    cooking_time: "25 - 30 minutes",
    nutrition: {
      calories: 520,
      carbohydrates: 56,
      protein: 20,
      fat: 27,
    },
  },
  {
    name: "Quinoa Bowl with Avocado Dressing",
    type: "lunch",
    servings: 1,
    ingredients: [
      "Cooked quinoa",
      "shredded carrots",
      "cucumber",
      "parsley",
      "mint",
      "dry roasted pumpkin seeds",
      "salt",
      "pepper",
      "avocado",
      "plain Greek yogurt",
      "lemon juice",
      "garlic",
      "water",
    ],
    prep_time: "10 minutes",
    cooking_time: "0 minutes",
    nutrition: {
      calories: 551,
      carbohydrates: 64,
      protein: 18,
      fat: 27,
    },
  },
  {
    name: "Roasted Veggie Quinoa Salad",
    type: "lunch",
    servings: 1,
    ingredients: [
      "Quinoa",
      "cherry tomatoes",
      "red bell pepper",
      "sweet potato",
      "onion",
      "avocado oil",
      "turmeric",
      "cumin",
      "salt",
      "pepper",
      "sunflower seeds",
      "lemon juice",
      "fresh parsley",
    ],
    prep_time: "10 minutes",
    cooking_time: "20-25 minutes",
    nutrition: {
      calories: 466,
      carbohydrates: 69,
      protein: 15,
      fat: 16,
    },
  },
  {
    name: "Salsa Chicken 'Tacos'",
    type: "lunch",
    servings: 2,
    ingredients: [
      "Chicken breast",
      "red salsa",
      "iceberg lettuce",
      "avocado",
      "white onion",
    ],
    prep_time: "5 minutes",
    cooking_time: "4 hours",
    nutrition: {
      calories: 482,
      carbohydrates: 35,
      protein: 47,
      fat: 20,
    },
  },
  {
    name: "Savory Cabbage Salad w/ Baked Salmon",
    type: "lunch",
    servings: 2,
    ingredients: [
      "Green cabbage",
      "red cabbage",
      "carrots",
      "cilantro",
      "almonds",
      "sunflower seeds",
      "wild caught salmon",
      "salt",
      "pepper",
      "rice vinegar",
      "honey",
      "coconut aminos",
      "ginger root",
    ],
    prep_time: "5-10 minutes",
    cooking_time: "20 minutes",
    nutrition: {
      calories: 418,
      carbohydrates: 28,
      protein: 34,
      fat: 19,
    },
  },
  {
    name: "Tuna Avocado Salad",
    type: "lunch",
    servings: 1,
    ingredients: [
      "Organic arugula and spinach mix",
      "olive oil",
      "wild-caught tuna in water",
      "avocado",
      "everything bagel seasoning",
      "apple",
    ],
    prep_time: "5 minutes",
    cooking_time: "No cook",
    nutrition: {
      calories: 569,
      carbohydrates: 37,
      protein: 44,
      fat: 30,
    },
  },
  {
    name: "Bison Greek Skillet",
    type: "dinner",
    servings: 2,
    ingredients: [
      "3/4 lb (340 g) ground bison",
      "1 tbsp (14 g) olive oil",
      "1 small onion, finely chopped",
      "1 orange or red bell pepper, diced",
      "2 cloves garlic, minced",
      "1 tsp (1 g) dried oregano",
      "1 tsp (0.75 g) dried basil",
      "1/2 tsp (0.5 g) dried thyme",
      "1/2 tsp (1 g) ground ginger",
      "Salt and pepper to taste",
      "1 cup (180 g) fresh diced tomatoes",
      "1 cup (200 g) brown rice, cooked",
      "1 cup (30 g) spinach, chopped",
      "2 tbsp (30 g) crumbled goat cheese (optional)",
    ],
    prep_time: "10 minutes",
    cooking_time: "25 minutes",
    directions:
      "Cook brown rice according to the package. Warm a large skillet over medium-high heat. Add bison and cook until browned all the way through, crumbling and flipping as it cooks. Push the bison to the edge of the skillet and add olive oil, onion, bell pepper, and garlic. Cook for 4-5 minutes until vegetables begin to soften. Add oregano, basil, thyme, ginger, salt, pepper, and tomatoes. Mix together with the vegetables and the bison. Cook approximately 5 minutes. Add brown rice and spinach. Cook for 3-4 minutes. Serve warm, topped with crumbled goat cheese.",
    nutrition: {
      calories: 520,
      carbohydrates: 35,
      protein: 42,
      fat: 23,
    },
  },
  {
    name: "Chicken Meatballs with Roasted Veggies",
    type: "dinner",
    servings: 2,
    ingredients: [
      "3/4 lb (340 g) ground chicken",
      "1/2 small onion, minced",
      "2 garlic cloves, minced",
      "3 cups (450 g) fingerling potatoes, quartered",
      "10 small (500 g) carrots (or 5 large), halved lengthwise, peeled and stems removed",
      "2 cups (142 g) broccoli florets",
      "1 1/2 tbsp (21 g) avocado oil",
      "1/2 tbsp (3.5 g) onion powder",
      "1/2 tbsp (4.5 g) garlic powder",
      "1 tbsp (1.5 g) dried parsley",
      "1/2 tbsp (3.5 g) paprika",
    ],
    prep_time: "10 minutes",
    cooking_time: "25-30 minutes",
    directions:
      "Preheat oven to 400 degrees F (205 C). In a medium bowl, mix together ground chicken, minced onion, and garlic. Then create meatballs, 1 inch in diameter, and spread evenly on a large baking sheet. Add potatoes, carrots, and broccoli to the same baking sheet. Mix avocado oil, onion powder, garlic powder, parsley, and paprika. Pour oil mixture over vegetables and toss to coat well. Spread veggies into a single layer. Bake for 25-30 minutes until internal temperature of chicken reaches above 165 degrees F (65 C). Serve warm.",
    nutrition: {
      calories: 601,
      carbohydrates: 74,
      protein: 49,
      fat: 14,
    },
  },
  {
    name: "Garlic Shrimp and Greens",
    type: "dinner",
    servings: 2,
    ingredients: [
      "3/4 cup (140 g) white or brown rice (uncooked)",
      "12 oz (340 g) raw shrimp (peeled and deveined)",
      "1 tbsp (14 g) olive oil",
      "3 cloves garlic",
      "4 cups (270 g) kale (chopped)",
      "2 tbsp (30 g) lemon juice",
      "1/2 tbsp (8 g) apple cider vinegar",
      "salt and pepper to taste",
    ],
    prep_time: "10 minutes",
    cooking_time: "15-20 minutes",
    directions:
      "Cook rice as per package instructions. In a large skillet, warm olive oil over medium heat, add garlic and cook for 1 minute, then add kale, lemon juice, and apple cider vinegar. Cover and cook for 3-4 minutes. Uncover, push kale to one side, add shrimp, remaining lemon juice, salt, and pepper, cook for 2-3 minutes per side. Serve kale and shrimp over rice.",
    nutrition: {
      calories: 504,
      carbohydrates: 67,
      protein: 33,
      fat: 11,
    },
  },
  {
    name: "Lentil Beef Chili",
    type: "dinner",
    servings: 2,
    ingredients: [
      "3/4 lb (340 g) grass-fed organic ground beef (95% lean)",
      "2 cups (412 g) bone broth",
      "1/2 yellow onion",
      "1 red bell pepper",
      "3 garlic cloves",
      "1 15 oz (425 g) can crushed tomatoes",
      "1/2 cup (100 g) brown lentils",
      "1 tsp (2 g) cumin powder",
      "1/2 tsp (1 g) cayenne powder",
      "1/2 tsp (0.5 g) dried oregano",
      "salt and pepper to taste",
      "1/2 avocado for topping",
    ],
    prep_time: "10 minutes",
    cooking_time: "1 hour",
    directions:
      "Let ground beef come to room temperature (about 30 minutes). Finely dice onion, red pepper, and garlic. Wash lentils and set aside. In a pot, sauté ground beef in olive oil until cooked, transfer to a bowl. In the same pot, sauté onions, peppers, and garlic, then quickly add spices and broth to deglaze. Add lentils and tomatoes, cook without a lid for 40-50 minutes, checking every 20 minutes to add water if needed. Season and serve with avocado.",
    nutrition: {
      calories: 585,
      carbohydrates: 57,
      protein: 56,
      fat: 17,
    },
  },
  {
    name: "Curry Roasted Chickpea and Veggie Quinoa",
    type: "dinner",
    servings: 2,
    ingredients: [
      "1/2 cup quinoa (uncooked)",
      "1 cup water",
      "1 tsp olive oil",
      "1/2 tsp turmeric",
      "1/4 tsp ground cinnamon",
      "salt and pepper to taste",
      "1 tbsp avocado oil",
      "1 tsp honey",
      "juice of 1/2 lemon",
      "1 tsp red curry powder",
      "1/4 cup tahini",
      "1 15 oz can chickpeas (drained and rinsed)",
      "2 large beets (diced)",
      "1/2 medium red onion",
      "2 cups shredded red cabbage",
    ],
    prep_time: "10 minutes",
    cooking_time: "45 minutes",
    directions:
      "Preheat oven to 400°F (200°C). Cook quinoa with water, olive oil, turmeric, cinnamon, salt, and pepper. Mix avocado oil, honey, lemon, curry powder, tahini, and water. Coat chickpeas, beets, onion, and cabbage with the sauce. Bake for 15 minutes. Top cooked quinoa with the chickpea and veggie mixture.",
    nutrition: {
      calories: null,
      carbohydrates: null,
      protein: null,
      fat: null,
    },
  },
  {
    name: "Detox Soup",
    type: "dinner",
    servings: 2,
    ingredients: [
      "1 tbsp (14 g) olive oil",
      "3 cloves garlic (pressed or minced)",
      "1/2 tbsp (2.5 g) grated ginger",
      "1/2 small onion",
      "1 orange bell pepper",
      "1/2 tbsp (1 g) dried parsley",
      "1 tsp (1 g) oregano",
      "1/2 (3 g) tsp salt",
      "1/4 tsp (1 g) pepper",
      "3 cups (620 g) bone broth",
      "1 chicken breast (boneless and skinless)",
      "1/2 medium head of cauliflower (chopped)",
      "1 small zucchini (chopped)",
      "1 avocado (diced)",
    ],
    prep_time: "15 minutes",
    cooking_time: "30-35 minutes",
    directions:
      "Heat olive oil in a pot. Add garlic, ginger, and onion, cook for 2-3 minutes. Add bell pepper, parsley, oregano, salt, and pepper, cook until peppers soften. Add broth and chicken breast, cook for 20 minutes. Add cauliflower and zucchini, simmer for 5-7 minutes. Shred chicken and return to pot. Serve warm, topped with avocado.",
    nutrition: {
      calories: 435,
      carbohydrates: 30,
      protein: 24,
      fat: 26,
    },
  },
  {
    name: "Dill-icious Savory Salmon Soup",
    type: "dinner",
    servings: 2,
    ingredients: [
      "12 oz (340 g) salmon fillet (deboned and without skin, cubed)",
      "1 large russet potato",
      "1/2 yellow onion",
      "2 small celery stalks",
      "1 large carrot",
      "3 garlic cloves",
      "2.5 cups (600 g) fish or chicken broth",
      "1 small bunch broccoli",
      "2-3 tbsp (1.5 g) fresh dill",
      "2 tbsp (27 g) olive oil",
      "2 tbsp (30 g) organic canned coconut milk",
      "salt and pepper to taste",
    ],
    prep_time: "10 minutes",
    cooking_time: "25 minutes",
    directions:
      "Cut salmon into bite-size pieces, season with salt and pepper. Dice onion, celery, carrot, broccoli, and potato. Mince garlic and chop dill. Sauté onions, carrots, and celery in olive oil, add garlic. Add broth, potatoes, cook for 10-15 minutes. Add salmon and broccoli, cook for 5 minutes. Add coconut milk, season with dill, salt, and pepper.",
    nutrition: {
      calories: 524,
      carbohydrates: 35,
      protein: 45,
      fat: 24,
    },
  },
];

export {
  settings,
  AllergiesInformation,
  chronicConditions,
  foodTypeInformation,
  pinnedRecipes,
};
